### ISSUE TITLE
Exception: File not available in pvars module

### ISSUE THREAD

**Issue by RandomBananazz** [Znunu/EzMudae#2]
Trying to use your module for my autoclaiming bot (that you might remember a while back).

Can't seem to run it because it throws an exception upon running:
```
Traceback (most recent call last):
  File "Z:/discord_bot/WaifuBotV3/bot.py", line 25, in <module>
    from EzMudae import Mudae
  File "Z:\discord_bot\WaifuBotV3\EzMudae.py", line 8, in <module>
    pvars = pvars.get_context(file_format=pvars.Format.JSON)
  File "Z:\discord_bot\WaifuBotV3\pvars.py", line 168, in get_context
    ctx = ModuleContext(db_path)
  File "Z:\discord_bot\WaifuBotV3\pvars.py", line 109, in __init__
    self.db = PersistentDict(path, Format.PICKLE)
  File "Z:\discord_bot\WaifuBotV3\pvars.py", line 35, in __init__
    else: raise Exception("File not available")
Exception: File not available
```

Running Python 3.8 on Windows 10.

**Comment by Znunu** [comment]
Hiya!
Woah, it has been a while huh? I'm glad you're giving this a try. Thanks for the stack trace, it should be enough for me to investigate what's going on. You don't happen to have a discord I can add you on? Would be a bit faster than communicating here

**Comment by Znunu** [comment]
I've removed the dependency on that module. should work fine now
